name: Push

on:
    push:
        branches:
            - master

jobs:
    format:
        name: Format repository
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Prettify code
              uses: creyD/prettier_action@v4.3
              with:
                  prettier_options: --write .
                  commit_message: "gh-actions: format code"
                  github_token: ${{ secrets.GITHUB_TOKEN }}

    build_and_deploy:
        name: Build and Deploy Script
        runs-on: ubuntu-latest
        needs: format

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install dependencies
              run: npm ci

            - name: Run ESlint
              run: npm run lint

            - name: Build script
              run: npm run build-local

            - name: Prepare for deployment
              run: |
                  mkdir publish
                  mv -f dist/* README.md LICENSE publish/

            - name: Deploy script
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: dist
                  FOLDER: "publish"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
